name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Clear npm cache and remove node_modules directory
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Remove node_modules and babel-loader cache
        run: |
          rm -rf node_modules
          rm -rf node_modules/.cache/babel-loader

      - name: Install dependencies
        run: npm ci

      # Start the application
      - name: Start application
        run: npm start &
        env:
          NODE_ENV: development

      # Wait for the application to be ready
      - name: Wait for application to be ready
        run: |
          npx wait-on http://localhost:3000

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: false
          publish-summary: true
          component: false
