name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build

    # Add a Cypress installation step if Cypress isn't already installed in `npm ci`
    - name: Install Cypress
      run: npm install cypress --save-dev

    # Add a step to run Cypress tests
    - name: Run Cypress Tests
      run: npx cypress run
      env:
        # Required to run Cypress in CI
        CI: true
