name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - run: npm ci

    - run: npm run build

    - name: Start Application
      run: |
        npm start &> server.log &
        sleep 10
      env:
        CI: true

    - name: Check Server Logs
      run: cat server.log

    - name: Wait for Server
      run: npx wait-on http://localhost:3000 --timeout 60000

    - name: Run Cypress Tests
      run: npx cypress run --browser chrome
      env:
        CI: true
