name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build

    # Start the server in the background
    - name: Start Application
      run: npm start &
      env:
        CI: true

    # Wait for the server to be ready
    - name: Wait for Server
      run: npx wait-on http://localhost:3000

    # Run Cypress tests
    - name: Run Cypress Tests
      run: npx cypress run
      env:
        CI: true
